### PR TITLE
README: Fixup badges.

### PR DESCRIPTION
**Pull request by thorduri**
Drop the License blurb at the bottom, covered by the badge at the top.

### CODE REVIEW

**Comment by shurcooL** [comment]
This is not my repository, but I think it's better to keep the License section at the bottom, even if a badge displays it on top.

The bottom section is for looking for the license. The top is for convenience and may be overlooked.

**Comment by davecgh** [comment]
Thanks for the PR.  I noticed this was also fixed in #69 which I just merged, so going to close it.

**Comment by shurcooL** [comment]
I think you meant #64, not #69.

**Comment by davecgh** [comment]
Thanks @shurcooL.  That's correct.  I meant #64.

**Pull request closed without merging**
